[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 3 }
opacity = 0.90
blur = false
startup_mode = "SimpleFullscreen"

[scrolling]
history = 100000

[font]
size = 13
normal = { family = "Hack Nerd Font", style = "Regular" }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" }
]
